name: Maven Build

on:
  push:
    branches:
      - 10.10

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1500

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build . -t local_build_image

    - name: Setup Maven settings.xml
      run: |
        docker run --rm -v $GITHUB_WORKSPACE:/workspace -w /workspace local_build_image /bin/bash -c "\
        mkdir -p ~/.m2 && \
        cp /workspace/settings.xml ~/.m2/ && \
        echo 'Checking if settings.xml was copied...' && \
        if [ -f ~/.m2/settings.xml ]; then echo 'settings.xml successfully copied!'; else echo 'settings.xml copy failed!'; exit 1; fi"

    - name: Add Ant File
      run: |
        docker run --rm -v $GITHUB_WORKSPACE:/workspace -w /workspace local_build_image /bin/bash -c "\
        mvn install:install-file \
        -Dfile=/workspace/nuxeo/ant-assembly-maven-plugin-2.1.5.jar \
        -DpomFile=/workspace/nuxeo/ant-assembly-maven-plugin-2.1.5.pom \
        -DgroupId=org.nuxeo.build \
        -DartifactId=ant-assembly-maven-plugin \
        -Dversion=2.1.5 \
        -Dpackaging=jar"

    - name: Run Maven Build inside Docker container
      run: |
        docker run --rm -v $GITHUB_WORKSPACE:/workspace -w /workspace local_build_image /bin/bash -c "\
        mvn clean install -DskipTests -X -e"
