name: Maven Build

on:
  push:
    branches:
      - 10.10

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1500

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build . -t local_build_image

    - name: Run Maven Build inside Docker container
      run: |
        docker run --rm -v $PWD:/workspace -w /workspace local_build_image /bin/bash -c "\
        mvn clean install -DskipTests && \
        echo Building addons-core... && \
        cd addons-core && mvn clean install -DskipTests && cd .. && \
        echo Building addons POM only... && \
        cd addons && mvn clean install -N && cd .. && \
        echo Building nuxeo-dmk-adaptor... && \
        cd nuxeo-dmk-adaptor && mvn clean install -DskipTests && cd .. && \
        echo Building nuxeo-platform-lang-ext && \
        cd nuxeo-platform-lang-ext && mvn clean install -DskipTests && cd .. && \
        echo Building nuxeo-binary-metadata && \
        cd nuxeo-binary-metadata && mvn clean install -DskipTests && cd .. && \
        echo Building nuxeo-platform-suggestbox && \
        cd nuxeo-platform-suggestbox && mvn clean install -DskipTests && cd .. && \
        echo Building nuxeo-platform-document-routing... && \
        cd nuxeo-platform-document-routing && mvn clean install -DskipTests && cd .. && \
        echo Building nuxeo-chemistry... && \
        cd nuxeo-chemistry && mvn clean install -DskipTests && cd .. && \
        echo Building nuxeo-filesystem-connectors && \
        cd nuxeo-filesystem-connectors && mvn clean install -DskipTests && cd .. && \
        echo Building nuxeo-platform-pdf-utils... && \
        cd nuxeo-platform-pdf-utils && mvn clean install -DskipTests && cd .. && \
        echo Building nuxeo-apidoc-server... && \
        cd nuxeo-apidoc-server && mvn clean install -DskipTests && cd .. && \
        echo Building nuxeo-connect-tools... && \
        cd nuxeo-connect-tools && mvn clean install -DskipTests && cd .. && \
        echo Building nuxeo-logs-viewer... && \
        cd ../../../nuxeo-logs-viewer && git checkout release-10.10-HF62 && mvn clean install -DskipTests && cd .. && \
        echo Building nuxeo-shell... && \
        cd nuxeo-shell && git checkout release-10.10-HF62 && mvn clean install -DskipTests && cd .. && \
        echo Building nuxeo-startup-wizard... && \
        cd nuxeo/nuxeo-distribution/nuxeo-startup-wizard && mvn clean install -DskipTests && \
        echo Building nuxeo-startup-wizard POM only... && \
        mvn clean install -N && \
        echo Building nuxeo-distribution parent POM only... && \
        cd .. && mvn clean install -N && \
        echo Building nuxeo-nxr-server... && \
        cd nuxeo-nxr-server && mvn clean install -DskipTests && \
        echo Building nuxeo-nxr-server POM only... && \
        mvn clean install -N && cd .. && \
        echo Building nuxeo-nxr-jsf-ui... && \
        cd nuxeo-nxr-jsf-ui && mvn clean install -DskipTests && cd .. && \
        echo Building nuxeo-launcher... && \
        cd nuxeo-launcher && mvn clean install -DskipTests && cd .. && \
        echo Building nuxeo-server-tomcat... && \
        cd nuxeo-server-tomcat && mvn clean install -DskipTests && cd .. && \
        echo Building nuxeo-platform-audio.. && \
        cd ../../addons/nuxeo-platform-audio && mvn clean install -DskipTests && cd .. && \
        echo Building nuxeo-platform-video-api.. && \
        cd nuxeo-platform-video/nuxeo-platform-video-api && mvn clean install -DskipTests && cd .. && \
        echo Building nuxeo-platform-video.. && \
        mvn clean install -DskipTests && cd .. && \
        echo Building nuxeo-dam... && \
        cd nuxeo-dam/nuxeo-dam && mvn clean install -DskipTests && cd ../.. && \
        echo building nuxeo-common... && \
        cd ../../nuxeo-common && mvn clean install -DskipTests && cd .. && \
        echo Building nuxeo-core-api... && \
        cd nuxeo-core/nuxeo-core-api && mvn clean install -DskipTests && cd ../.. && \
        echo Building nuxeo-platform-filemanager-core && \
        cd nuxeo-services/nuxeo-platform-filemanager-core && mvn clean install -DskipTests && cd ../.. && \
        echo Building nuxeo-platform-audio-jsf... && \
        cd nuxeo-platform-audio/nuxeo-platform-audio-jsf && mvn clean install -DskipTests"
